### ISSUE TITLE
How do I post my UML image?

### ISSUE THREAD

**Issue by CodeSculptor1** [Team-3-HW-2/UML#5]
I can't find how to make a folder or post my UML png. I've tried the "+" for making a new file, but it just does git.

**Comment by KnightPickles** [comment]
You have to use the command line to actually upload an image to the repo. At least, as far as I understand it. You can, however, upload an image like I did through the issues interface. If you navigate to submit a new issue, you'll notice the box you normally type in also says "Attach images by dragging and dropping..." at the bottom. Simply drag your .png image into the text box and select the comment button. Use preview to view it before submission. :)

**Comment by LizHernandez** [comment]
![hw2-all_cases](https://cloud.githubusercontent.com/assets/10604231/5993586/b9018e9e-aa0a-11e4-9a4b-75951953e97e.png)

**Comment by LizHernandez** [comment]
Thanks :)

**Comment by CodeSculptor1** [comment]
Thanks :)
